name: Build Xpra AppImage

on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build (default: master)'
        required: false
        default: 'master'
  push:
    branches:
      - master
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build scripts
        uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 python3-pip # add more as needed

      - name: Run build script
        run: |
          ./run_local.sh
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: xpra-appimage
          path: ./xpra-latest.AppImage
