name: Weekly Xpra AppImage Build

on:
  schedule:
    - cron: '0 6 * * 1' # every Monday at 06:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build scripts
        uses: actions/checkout@v4
      - name: Print env
        run: |
          echo "[GH runner]"
          df -h
          pwd
          ls -la
      - name: Fix workspace permissions
        run: sudo chmod 777 ${{ github.workspace }}
      - name: Run build script
        run: |
          docker build -f Dockerfile.centos8 -t xpra-appimg-builder-centos8 .
          docker run --rm -v ${{ github.workspace }}:/workspace xpra-appimg-builder-centos8
          df -h
          pwd
          ls -la
          echo "[GH runner] Build complete"
          ls -ld ${{ github.workspace }}
          ls -lAh ${{ github.workspace }}/build

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: xpra-appimage
          path: ${{ github.workspace }}/build/Xpra-x86_64.AppImage

      - name: Get week and date
        id: weekdate
        run: |
          echo "week=$(date +%V)" >> $GITHUB_OUTPUT
          echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: weekly-build-${{ github.run_number }}
          release_name: "Weekly Xpra Build ${{ steps.weekdate.outputs.week }} [#${{ github.run_number }}] ${{ steps.weekdate.outputs.date }}"
          draft: false
          prerelease: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/build/Xpra-x86_64.AppImage
          asset_name: xpra-weekly-${{ github.run_number }}.AppImage
          asset_content_type: application/octet-stream
